In [1]:
import numpy as np
from anaconda_project.internal.conda_api import result
from dask.array import maximum, nan_to_num, reshape
from mpmath import arange

In [2]:
list1 = [1,2,3,4]
oneArray = np.array(list1)
print(type(oneArray))
oneArray

<class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [4]:
oneArray = np.array([1,2,3])
print(type(oneArray))
print(oneArray)

<class 'numpy.ndarray'>
[1 2 3]


In [5]:
t3 = np.arange(0,10,2)
print(t3)
print(type(t3))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [7]:
list2 = [[1,2],[3,4],[5,6]]
t4 = np.array(list2)
print(t4)
print(t4.ndim) #唯度
print(t4.shape)
print(t4.size)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
6


In [15]:
t5 = np.array([[1,2,3],[4,5,6]])

print(t5)
t5.shape = (3,2)
print(t5)

t5 = np.array([[1,2,3],[4,5,6]])
t = t5.reshape(3,2)
print(t5)

t6 = t5.reshape((6,))
print(t6)
t6 = t5.reshape((6,),order='F')
t6
t7 = t5.flatten(order='F')
t7

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


array([1, 4, 2, 5, 3, 6])

In [19]:
t8 = np.arange(24)
print(t8)
t8.shape = (4,6)
print(t8)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [21]:
a = t8.tolist()
print(type(a))
a

<class 'list'>


[[0, 1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10, 11],
 [12, 13, 14, 15, 16, 17],
 [18, 19, 20, 21, 22, 23]]

In [27]:
import random
f = np.array([1,2,3,4,5],dtype=np.int16)
print(f.itemsize)
print(f)
print(f.dtype)
f1 = f.astype(np.int64)
print(f1.dtype)
print(round(random.random(),2)) #生成0-1之间的随机数,保留两位小数
arr  = np.array([random.random() for i in range(10)]) #生成10个0-1之间的随机数,保留两位小数,并组成数组
print(type(arr))
print(arr)
print(np.round(arr,2)) #保留两位小数,并返回数组,与round()函数不同,round()函数只对单个数字有效

2
[1 2 3 4 5]
int16
int64
0.88
<class 'numpy.ndarray'>
[0.78150052 0.38298902 0.02317304 0.84185906 0.7127973  0.31593057
 0.20245548 0.0804395  0.16561571 0.68820568]
[0.78 0.38 0.02 0.84 0.71 0.32 0.2  0.08 0.17 0.69]


## 数组运算

In [28]:
t9 = np.arange(24).reshape(4,6)
print(t9)
print(t9+2)
print(t9*2)
print(t9/2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]
 [14 15 16 17 18 19]
 [20 21 22 23 24 25]]
[[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]
 [24 26 28 30 32 34]
 [36 38 40 42 44 46]]
[[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]


In [29]:
t10 = np.arange(24).reshape(4,6)
t11 = np.arange(100,124).reshape(4,6)
print(t10 + t11)
print(t10 - t11)

[[100 102 104 106 108 110]
 [112 114 116 118 120 122]
 [124 126 128 130 132 134]
 [136 138 140 142 144 146]]
[[-100 -100 -100 -100 -100 -100]
 [-100 -100 -100 -100 -100 -100]
 [-100 -100 -100 -100 -100 -100]
 [-100 -100 -100 -100 -100 -100]]


In [30]:
a1 = np.arange(24).reshape(4,6)
a2 = np.arange(6)
print(a1)
print(a2)
print(a1 + a2)
print(a1 * a2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[0 1 2 3 4 5]
[[ 0  2  4  6  8 10]
 [ 6  8 10 12 14 16]
 [12 14 16 18 20 22]
 [18 20 22 24 26 28]]
[[  0   1   4   9  16  25]
 [  0   7  16  27  40  55]
 [  0  13  28  45  64  85]
 [  0  19  40  63  88 115]]


In [31]:
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(4).reshape((4,1))
print(t1)
print(t2)
print(t1 -t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


In [33]:
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

[5 7 9]
[ 6 15]


In [38]:
a = np.arange(8)
print(a)
print(a[2],a)
print(a[2:])
print(a[:2])

[0 1 2 3 4 5 6 7]
2 [0 1 2 3 4 5 6 7]
[2 3 4 5 6 7]
[0 1]


In [64]:
a = np.arange(24).reshape(4,6)
print(a[1],a)
print('-'*20)
print(a[1,:],'\n','-'*20,'\n',a[1:3])
print(a[0:3])
print(a[:,1])
print(a[0,3])

[ 6  7  8  9 10 11] [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------
[ 6  7  8  9 10 11] 
 -------------------- 
 [[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[ 1  7 13 19]
3


In [68]:
t = np.arange(24).reshape(4,6)
print(t)
t[1,:] = 0
print(t)
t[1:3,:] = 0
print(t)
t[1:] = 0
print(t)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 0  0  0  0  0  0]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [18 19 20 21 22 23]]
[[0 1 2 3 4 5]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [75]:
t = np.arange(24).reshape(4,6)
t[:,1] = 0
print(t)
t[:,1:3] = 0
print(t)

[[ 0  0  2  3  4  5]
 [ 6  0  8  9 10 11]
 [12  0 14 15 16 17]
 [18  0 20 21 22 23]]
[[ 0  0  0  3  4  5]
 [ 6  0  0  9 10 11]
 [12  0  0 15 16 17]
 [18  0  0 21 22 23]]


In [78]:
t = np.arange(24).reshape(4,6)
t[(t < 7) & (t  > 2)]  = 0
print(t)
t[t > 2] = 0
print(t)

[[ 0  1  2  0  0  0]
 [ 0  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0 1 2 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [82]:
score = np.array([[80,81],[75,87],[90,68]])
result = np.where(score > 80 , True, False)
print(result)

[[False  True]
 [False  True]
 [ True False]]


In [85]:
t = np.arange(24).reshape(4,6)
t.clip(10,18)
t
print(t.clip(10,18))

[[10 10 10 10 10 10]
 [10 10 10 10 10 11]
 [12 13 14 15 16 17]
 [18 18 18 18 18 18]]


In [92]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(np.append(a,[7,8,9]).shape)
print(a.shape)
print(np.append(a,[[7,8,9]],axis=0))
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))

[[1 2 3]
 [4 5 6]]
(9,)
(2, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [97]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(np.insert(a,3,[11,12]))
print(np.insert(a,1,11,axis=0))
print(np.insert(a,1,11,axis=1))

[ 1  2  3 11 12  4  5  6]
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [99]:
a = np.arange(12).reshape(3,4)
print(np.delete(a,5))
print(np.delete(a,1,axis=1))


[ 0  1  2  3  4  6  7  8  9 10 11]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [103]:
a = np.array([5,2,6,2,7,5,6,8,2,9])
print(a)
u = np.unique(a)
print(u)
u,indexs = np.unique(a,return_index=True)
print(indexs)
u,num = np.unique(a,return_counts=True)
print(num)

[5 2 6 2 7 5 6 8 2 9]
[2 5 6 7 8 9]
[1 0 2 4 7 9]
[3 2 2 1 1 1]


In [112]:
score = np.array([[80,88],[82,81],[75,81]])
print(np.max(score))
print(np.max(score,axis=1))
result = np.maximum([-2, -1, 0, 1, 2], 0)
print(result)
result = np.minimum([-2, -1, 0, 1, 2], 0)
print(result)
result = np.maximum( [-2, -1, 0, 1, 2], [1, 2, 3, 4, 5] )
print(result)
print(np.mean(score))
print(np.mean(score,axis=1))


88
[88 82 81]
[0 0 0 1 2]
[-2 -1  0  0  0]
[1 2 3 4 5]
81.16666666666667
[84.  81.5 78. ]


In [126]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print(arr.cumsum(0))
print(arr.cumsum(1))
result = np.argmax(arr,axis=0)
res  = np.min(arr,axis=0)
print(result,res)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]
[1 1 1] [1 2 3]


In [128]:
result = np.std(arr,axis=1) #计算标准差
print(result)

[0.81649658 0.81649658]


In [129]:
result = np.ptp(score) # 最大值与最小值的差
print(result)

13


In [138]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.concatenate((a,b)))
print(np.concatenate((a,b),axis=0))
print(np.concatenate((a,b),axis=1))
print(np.stack((a,b),axis=0))
print(np.shape(np.stack((a,b),axis=0)))
print(np.stack((a,b),axis=1))
print(np.shape(np.stack((a,b),axis=1)))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
(2, 2, 2)


In [140]:
v1 = [[0,1,2,3,4,5],
[6,7,8,9,10,11]]
v2 = [[12,13,14,15,16,17],
[18,19,20,21,22,23]]
print(np.vstack((v1,v2))) #垂直堆叠
print(np.hstack((v1,v2))) #水平堆叠

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]


In [141]:
arr = np.arange(9).reshape(3,3)
print ('将数组分为三个大小相等的子数组：')
b = np.split(arr,3)
print(b)


将数组分为三个大小相等的子数组：
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


In [144]:
harr = np.floor(10*np.random.random((2, 6))) #生成一个 2 行 6 列的二维数组,这些随机浮点数的范围是 [0.0, 1.0)
print(harr)
print(np.hsplit(harr,3))
print(np.vsplit(harr,2))

[[4. 4. 0. 4. 0. 8.]
 [7. 4. 7. 0. 8. 0.]]
[array([[4., 4.],
       [7., 4.]]), array([[0., 4.],
       [7., 0.]]), array([[0., 8.],
       [8., 0.]])]
[array([[4., 4., 0., 4., 0., 8.]]), array([[7., 4., 7., 0., 8., 0.]])]


In [149]:
a = np.nan
b = np.inf
print(a,type(a))
print(b,type(b))
t = np.arange(24,dtype=float).reshape(4,6)
t[3,4] = np.nan
print(t)
print(np.count_nonzero(t))
print(np.count_nonzero(t!=t))
t[np.isnan(t)] = 0
print(t)

nan <class 'float'>
inf <class 'float'>
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. nan 23.]]
23
1
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21.  0. 23.]]


In [157]:
# t = np.arange(24).reshape(4,6).astype(float)
# print(t)
t = np.arange(24).reshape(4,6).astype('float')#单引号加不加没有影响
print(t)
t[1,3:] = np.nan
print(t)
for i in range(t.shape[1]): #t.shape[1] 取得形状元组的第二个元素，即列数，这里是 6，循环是一个0～5的序列
    temp_col = t[:,i] #一个数组
    nan_num = np.count_nonzero(temp_col != temp_col)
    if nan_num != 0:
        temp_col_not_nan = temp_col[temp_col == temp_col] #一个只包含原始列中非 NaN 值的数组。
        temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)
t

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8., 13., 14., 15.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [166]:
a = np.arange(12).reshape(3,4)
print(a)
print (np.transpose(a)) #转置
print(a.T)
print(a.swapaxes(1,0))
t = np.arange(27).reshape(3,3,3)
print(t)
t=np.rollaxis(t,2,0)
print(t)
print(t.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  3  6]
  [ 9 12 15]
  [18 21 24]]

 [[ 1  4  7]
  [10 13 16]
  [19 22 25]]

 [[ 2  5  8]
  [11 14 17]
  [20 23 26]]]
(3, 3, 3)
